[package]
name = "books_daemon"
version = "0.1.0"
authors = ["Bartosz Zbytniewski <bartosz.zbytniewski.dev@gmail.com>"]
edition = "2021"

[dependencies]
daemonize = "0.4.1"
notify = "4.0.15"
anyhow = "1.0.28"
dirs = "4.0.0"
config = "0.10.1"
serde = { version =  "1.0.106", features = ["derive"] }
